MIN_BASE_HR = 50
MAX_BASE_HR = 85
MIN_MAX_HR = 100
MAX_MAX_HR = 130
MIN_MAX_INCREASE = 2
MAX_MAX_INCREASE = 4
MIN_MAX_DECREASE = 2
MAX_MAX_DECREASE = 4

MIN_FREQ = 50
MAX_FREQ = 255

MIN_FREQ_TOLERANCE = 10
MAX_FREQ_TOLERANCE = 100
MIN_FREQ_SLOPE = 5
MAX_FREQ_SLOPE = 20
PROFILE_CHANGE_INTERVAL = 50
STEP_MEMORY_SIZE = 10

NB_MOTIF = 5